### ISSUE TITLE
坑的吧。。。。

### ISSUE THREAD

**Issue by 401885064** [thinkSky1206/MaterialDesignLearn#2]
入口界面乱，找都找不到 <RecyclerView实现瀑布流布局> 相关代码     程序还一点注释都没。。。晕死。。。。。。。

**Comment by web3citizen** [comment]
不好意思  这是博客文章日常练习的demo代码 不是很规范  大部分java文件都是十几行  如果还是看不懂  那我有空把它删掉吧
